    
    $.writeln(Folder.desktop);
    
    var list = {
 '1793': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white','black'], Colors: ['orange','gold','red','royal','dark green','grey','maroon','navy','white','black'], Designs: ['script','block','adidas','collegiate','mascot'], FeeItem: 'LOGO01'},
 '10648': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['navy','grey','black','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10649': { Process: 'emb', DefaultPrimaryColor: 'charcoal', CommonColors: ['black','charcoal'], Colors: ['red','dark green','royal','navy','black','charcoal','purple'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10650': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10651': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '10652': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '10653': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['royal','navy','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10654': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10655': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white','black'], Colors: ['red','dark green','royal','navy','purple','black','white','grey','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10656': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','maroon','athletic gold','dark green','royal','navy','black','grey','white','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10657': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['royal','navy','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10658': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','royal','navy','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10659': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','navy','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10660': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['royal','navy','black','grey','red'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10661': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '10662': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10663': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '10665': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','grey'], Colors: ['black','grey'], Designs: ['design1'], FeeItem: ''},
 '10666': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['black','white','grey'], Colors: ['kelly green','navy','red','royal','maroon','black','white','grey'], Designs: ['headwear','mascot'], FeeItem: 'LogoHat01'},
 '10667': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '10672': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['grey','black'], Colors: ['black','grey','red'], Designs: ['design1'], FeeItem: ''},
 '10675': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '10679': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '10680': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','royal','navy','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '10681': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '10682': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['yellow','royal','black','white','orange'], Designs: ['design1'], FeeItem: ''},
 '10683': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '11689': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '11690': { Process: 'uv', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '11691': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '11702': { Process: 'uv', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '12722': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['athletic gold','black','grey'], Designs: ['design1'], FeeItem: ''},
 '12723': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['black','grey'], Designs: ['design1'], FeeItem: ''},
 '12759': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','dark green','royal','navy','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12769': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['grey','black','white'], Colors: ['grey','black','white','red','navy','kelly green','purple'], Designs: ['design1'], FeeItem: ''},
 '12770': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','dark green','royal','navy','purple','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12772': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','navy'], Colors: ['navy','black','grey'], Designs: ['design1'], FeeItem: ''},
 '12774': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['black','grey'], Designs: ['design1'], FeeItem: ''},
 '12775': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','royal','navy','black','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12776': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','royal','black','white','navy'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12779': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '12780': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12781': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['grey two','black','raw gold','grey three','navy'], Colors: ['grey two','black','raw gold','grey three','navy'], Designs: ['design1'], FeeItem: ''},
 '12782': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','royal','navy','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12783': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['dark green','royal','black','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12786': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12787': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12788': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12789': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['dark green','black','grey','navy','red','royal','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12835': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '12837': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12838': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12839': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','maroon','dark green','royal','navy','purple','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12840': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','navy','black','grey','white'], Designs: ['design1'], FeeItem: ''},
 '12841': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','white','graphite','grey'], Colors: ['black','white','graphite','navy','grey','dark green','red'], Designs: ['design1'], FeeItem: ''},
 '12843': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '12845': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '12846': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '12848': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '12851': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12854': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12855': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12856': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12857': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12858': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12866': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['red','dark green','royal','navy','purple','black','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12882': { Process: 'ht', DefaultPrimaryColor: 'grey', CommonColors: ['white','grey','black'], Colors: ['red','royal','navy','white','black','grey','dark green'], Designs: ['design8','design9'], FeeItem: 'Golfbag05'},
 '12884': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['white','black','grey'], Colors: ['white','black','grey','navy'], Designs: ['design1'], FeeItem: ''},
 '12896': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '12897': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '12898': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12915': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12916': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '12918': { Process: 'ht', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1','design10'], FeeItem: 'HEATTRAN01'},
 '12919': { Process: 'ht', DefaultPrimaryColor: 'black', CommonColors: ['black','white'], Colors: ['black','navy','royal','white'], Designs: ['design1','design10'], FeeItem: 'HEATTRAN01'  },
 '12940': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey'], Colors: ['dark green','kelly green','black','burgundy','grey','maroon','navy','royal'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12941': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['kelly green','black','burgundy','navy','royal'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12942': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['dark green','kelly green','black','grey','navy','royal'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12943': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['black','grey','navy','red','royal','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12947': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white','black'], Colors: ['red','navy','royal','maroon','white','grey','black','dark green'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12948': { Process: 'emb', DefaultPrimaryColor: 'charcoal', CommonColors: ['charcoal','black','white'], Colors: ['dark green','white','red','maroon','royal','black','charcoal','navy','gold','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12949': { Process: 'emb', DefaultPrimaryColor: 'charcoal', CommonColors: ['charcoal','black','white'], Colors: ['dark green','white','red','maroon','royal','black','charcoal','navy'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12950': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white','black'], Colors: ['red','navy','royal','maroon','white','grey','black','dark green'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '12952': { Process: 'emb', DefaultPrimaryColor: 'charcoal', CommonColors: ['black','charcoal','white'], Colors: ['dark green','black','charcoal','maroon','navy','purple','red','royal','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12959': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['black','grey','navy'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12974': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['black','grey','maroon','navy','red','royal'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '12993': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'  },
 '12994': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'  },
 '12996': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'  },
 '12997': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'  },
 '1799': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white','black'], Colors: ['orange','gold','red','royal','dark green','grey','maroon','navy','white','black','purple'], Designs: ['script','block','adidas','collegiate','mascot'], FeeItem: 'LOGO01'},
 '1828': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white','dark green','navy','orange','red','royal'], Designs: ['script','block','adidas','collegiate','mascot'], FeeItem: 'LOGO01'},
 '1829': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black','dark green','navy','orange','purple','red','royal','gold','maroon'], Designs: ['script','block','adidas','collegiate','mascot'], FeeItem: 'LOGO01'},
 '1850': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['white','black','grey'], Colors: ['red','orange','dark green','navy','grey','white','black'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '1852': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['maroon','orange','dark green','royal','navy','black'], Designs: ['script','block','collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '1892': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['white','black','grey'], Colors: ['purple','royal','navy','dark green','maroon','red','black','grey','white'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '2000': { Process: 'dtg', DefaultPrimaryColor: 'grey', CommonColors: ['white','black','grey'], Colors: ['columbia','dark green','athletic gold','yellow','kelly green','maroon','orange','purple','royal','red','navy','grey','white','black'], Designs: ['design6','design7','design8','design9','design10'], FeeItem: 'TMPLTD2G'},
 '226T': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['white','black'], Colors: ['white','black','dark green','maroon','navy','orange','purple','red','royal'], Designs: ['script','block','adidas','collegiate','mascot'], FeeItem: 'LOGO01'},
 '2667': { Process: 'none', DefaultPrimaryColor: 'vegas gold', CommonColors: ['vegas gold'], Colors: ['vegas gold'], Designs: ['design1'], FeeItem: ''},
 '2668': { Process: 'none', DefaultPrimaryColor: 'cardinal', CommonColors: ['cardinal','navy','gold'], Colors: ['cardinal','navy','gold'], Designs: ['design1'], FeeItem: ''},
 '2684': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '2688': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '2703': { Process: 'none', DefaultPrimaryColor: 'yellow', CommonColors: ['yellow'], Colors: ['yellow'], Designs: ['design1'], FeeItem: ''},
 '2704': { Process: 'none', DefaultPrimaryColor: 'dark green', CommonColors: ['yellow','dark green'], Colors: ['yellow','dark green'], Designs: ['design1'], FeeItem: ''},
 '2706': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white','red'], Colors: ['white','red'], Designs: ['design1'], FeeItem: ''},
 '2707': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal'], Colors: ['royal'], Designs: ['design1'], FeeItem: ''},
 '2708': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['royal','black','grey','red','navy','khaki'], Colors: ['royal','black','grey','red','navy','khaki'], Designs: ['design1'], FeeItem: ''},
 '2715': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white','royal','red','navy','yellow'], Colors: ['black','white','royal','red','navy','yellow'], Designs: ['design1'], FeeItem: ''},
 '2716': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','columbia','white','red'], Colors: ['black','columbia','white','red'], Designs: ['design1'], FeeItem: ''},
 '2717': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','royal','white','red','navy','yellow','dark green'], Colors: ['black','royal','white','red','navy','yellow','dark green'], Designs: ['design1'], FeeItem: ''},
 '2718': { Process: 'none', DefaultPrimaryColor: 'navy', CommonColors: ['navy'], Colors: ['navy'], Designs: ['design1'], FeeItem: ''},
 '2720': { Process: 'none', DefaultPrimaryColor: 'columbia', CommonColors: ['columbia'], Colors: ['columbia'], Designs: ['design1'], FeeItem: ''},
 '2721': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['black','white','navy','khaki'], Colors: ['black','white','navy','khaki'], Designs: ['design1'], FeeItem: ''},
 '2722': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '2723': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white','black'], Colors: ['white','black'], Designs: ['design1'], FeeItem: ''},
 '2749': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red','cardinal'], Colors: ['red','cardinal'], Designs: ['design1'], FeeItem: ''},
 '2751': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '2755': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['khaki'], Colors: ['khaki'], Designs: ['design1'], FeeItem: ''},
 '2763': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white','red','navy','yellow'], Colors: ['black','white','red','navy','yellow'], Designs: ['design1'], FeeItem: ''},
 '2764': { Process: 'none', DefaultPrimaryColor: 'columbia', CommonColors: ['columbia','navy','pink'], Colors: ['columbia','navy','pink'], Designs: ['design1'], FeeItem: ''},
 '2769': { Process: 'none', DefaultPrimaryColor: 'navy', CommonColors: ['navy'], Colors: ['navy'], Designs: ['design1'], FeeItem: ''},
 '2770': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white','navy'], Designs: ['design1'], FeeItem: ''},
 '2771': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black','columbia'], Designs: ['design1'], FeeItem: ''},
 '2772': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '2776': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '2818': { Process: 'none', DefaultPrimaryColor: 'navy', CommonColors: ['navy'], Colors: ['navy'], Designs: ['design1'], FeeItem: ''},
 '2823': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','columbia','purple'], Colors: ['black','columbia','purple'], Designs: ['design1'], FeeItem: ''},
 '2833': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['khaki','black','navy'], Colors: ['khaki','black','navy'], Designs: ['design1'], FeeItem: ''},
 '2859': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white','gold','dark green'], Colors: ['white','gold','dark green'], Designs: ['design1'], FeeItem: ''},
 '2862': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red','gold'], Colors: ['red','gold'], Designs: ['design1'], FeeItem: ''},
 '2876': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '2905': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['royal','white','red','navy'], Colors: ['royal','white','red','navy'], Designs: ['design1'], FeeItem: ''},
 '2930': { Process: 'none', DefaultPrimaryColor: 'dark green', CommonColors: ['dark green'], Colors: ['dark green'], Designs: ['design1'], FeeItem: ''},
 '2973': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white'], Colors: ['red','royal','navy','grey','white'], Designs: ['headwear','mascot'], FeeItem: 'LogoBeanie01'},
 '3101': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red'], Colors: ['red'], Designs: ['design1'], FeeItem: ''},
 '3102': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '3104': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '3112': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '3118': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['khaki','white'], Colors: ['khaki','white'], Designs: ['design1'], FeeItem: ''},
 '3120': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '3122': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['khaki'], Colors: ['khaki'], Designs: ['design1'], FeeItem: ''},
 '3198': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','purple','red','orange','navy','dark green'], Colors: ['royal','grey','purple','red','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '3300': { Process: 'none', DefaultPrimaryColor: 'gold', CommonColors: ['gold'], Colors: ['gold'], Designs: ['design1'], FeeItem: ''},
 '3301': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple','red'], Colors: ['purple','red'], Designs: ['design1'], FeeItem: ''},
 '3302': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','purple','red','kelly green'], Colors: ['black','royal','purple','red','kelly green'], Designs: ['design1'], FeeItem: ''},
 '3304': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','gold'], Colors: ['grey','gold'], Designs: ['design1'], FeeItem: ''},
 '3306': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','red','navy','columbia'], Colors: ['black','royal','grey','red','navy','columbia'], Designs: ['design1'], FeeItem: ''},
 '3307': { Process: 'none', DefaultPrimaryColor: 'columbia', CommonColors: ['columbia','navy'], Colors: ['columbia','navy'], Designs: ['design1'], FeeItem: ''},
 '3311': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','purple','white','red','orange','navy','yellow'], Colors: ['black','purple','white','red','orange','navy','yellow'], Designs: ['design1'], FeeItem: ''},
 '3312': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','purple','red','navy'], Colors: ['black','purple','red','navy'], Designs: ['design1'], FeeItem: ''},
 '3313': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','columbia','royal','white','red','gold','yellow'], Colors: ['black','columbia','royal','white','red','gold','yellow'], Designs: ['design1'], FeeItem: ''},
 '3314': { Process: 'none', DefaultPrimaryColor: 'green', CommonColors: ['kelly green'], Colors: ['kelly green'], Designs: ['design1'], FeeItem: ''},
 '3317': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal'], Colors: ['royal'], Designs: ['design1'], FeeItem: ''},
 '3320': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['black','grey','white','khaki'], Colors: ['black','grey','white','khaki'], Designs: ['design1'], FeeItem: ''},
 '3321': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white','columbia','black'], Colors: ['white','columbia','black'], Designs: ['design1'], FeeItem: ''},
 '3720': { Process: 'dtg', DefaultPrimaryColor: 'white', CommonColors: ['white','black','grey'], Colors: ['grey','black','white','dark green','athletic gold','maroon','navy','orange','purple','red','royal'], Designs: ['design1','design2','design3','design4','design5'], FeeItem: 'TMPLTD2G'},
 '3scqz': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['dark green','grey','red'], Designs: ['script','block','adidas','collegiate','mascot'], FeeItem: 'LOGO01'},
 '3slt': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['white','black','grey'], Colors: ['royal','black','red','black','grey','white','navy'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '3sPolo': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black','white'], Colors: ['black','navy','white'], Designs: ['script','block','adidas','collegiate','mascot'], FeeItem: 'LOGO01'},
 '4635': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '4636': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal','purple','red','maroon','navy','gold'], Colors: ['royal','purple','red','maroon','navy','gold'], Designs: ['design1'], FeeItem: ''},
 '4640': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','columbia','purple','red','maroon','orange','navy','gold'], Colors: ['black','columbia','purple','red','maroon','orange','navy','gold'], Designs: ['design1'], FeeItem: ''},
 '4641': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red','orange'], Colors: ['red','orange'], Designs: ['design1'], FeeItem: ''},
 '4646': { Process: 'none', DefaultPrimaryColor: 'navy', CommonColors: ['navy'], Colors: ['navy'], Designs: ['design1'], FeeItem: ''},
 '4648': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '4651': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal','navy'], Colors: ['royal','navy'], Designs: ['design1'], FeeItem: ''},
 '4654': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '4676': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple','royal'], Colors: ['purple','royal'], Designs: ['design1'], FeeItem: ''},
 '4678': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','purple','red','maroon','dark green'], Colors: ['grey','purple','red','maroon','dark green'], Designs: ['design1'], FeeItem: ''},
 '4681': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal'], Colors: ['royal'], Designs: ['design1'], FeeItem: ''},
 '4682': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '4683': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','purple','white','red','cardinal','dark green'], Colors: ['black','royal','grey','purple','white','red','cardinal','dark green'], Designs: ['design1'], FeeItem: ''},
 '4752': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','purple','red','maroon','orange','navy','dark green'], Colors: ['black','royal','purple','red','maroon','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '4782': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '4785': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','red','maroon'], Colors: ['black','red','maroon'], Designs: ['design1'], FeeItem: ''},
 '5073': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','white','red'], Colors: ['royal','grey','white','red'], Designs: ['design1'], FeeItem: ''},
 '5108': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','maroon','dark green','royal','navy','purple','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '5114': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','maroon','dark green','royal','navy','purple','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '5125': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','athletic gold','dark green','royal','navy','purple','black','white','orange','pink'], Designs: ['headwear','mascot'], FeeItem: 'LogoHat01'},
 '5128': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','athletic gold','dark green','royal','navy','purple','black','grey','white','orange'], Designs: ['headwear','mascot'], FeeItem: 'LogoHat01'},
 '5131': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','athletic gold','dark green','navy','purple','black','grey','white','royal','orange'], Designs: ['headwear','mascot'], FeeItem: 'LogoVisor01'},
 '5140': { Process: 'none', DefaultPrimaryColor: 'green', CommonColors: ['kelly green'], Colors: ['kelly green'], Designs: ['design1'], FeeItem: ''},
 '5141': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','red','orange','navy','celtic'], Colors: ['black','royal','red','orange','navy','celtic'], Designs: ['design1'], FeeItem: ''},
 '5142': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','columbia','grey','cardinal','orange'], Colors: ['black','columbia','grey','cardinal','orange'], Designs: ['design1'], FeeItem: ''},
 '5146': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','columbia','grey','white','navy'], Colors: ['black','columbia','grey','white','navy'], Designs: ['design1'], FeeItem: ''},
 '5147': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['grey','black','white'], Designs: ['design1'], FeeItem: ''},
 '5150': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '5151': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','navy'], Colors: ['black','navy'], Designs: ['design1'], FeeItem: ''},
 '5152': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','red','navy'], Colors: ['black','royal','red','navy'], Designs: ['design1'], FeeItem: ''},
 '5153': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red'], Colors: ['red'], Designs: ['design1'], FeeItem: ''},
 '5160': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal','red'], Colors: ['royal','red'], Designs: ['design1'], FeeItem: ''},
 '5161': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '5172': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple','red'], Colors: ['purple','red'], Designs: ['design1'], FeeItem: ''},
 '5266': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '5268': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '5352': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['grey','black'], Designs: ['design1'], FeeItem: ''},
 '5356': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal'], Colors: ['royal'], Designs: ['design1'], FeeItem: ''},
 '5360': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white'], Colors: ['grey','white'], Designs: ['design1'], FeeItem: ''},
 '5394': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','orange','navy','dark green'], Colors: ['black','grey','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '5395': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','purple','red','maroon','dark green'], Colors: ['black','purple','red','maroon','dark green'], Designs: ['design1'], FeeItem: ''},
 '5396': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','purple','red','orange','navy','gold','dark green'], Colors: ['black','royal','purple','red','orange','navy','gold','dark green'], Designs: ['design1'], FeeItem: ''},
 '5398': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','red','orange','gold'], Colors: ['black','royal','red','orange','gold'], Designs: ['design1'], FeeItem: ''},
 '5399': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','purple','red','maroon','orange','navy','gold','dark green'], Colors: ['black','purple','red','maroon','orange','navy','gold','dark green'], Designs: ['design1'], FeeItem: ''},
 '5400': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','purple','red','maroon','orange','navy','dark green'], Colors: ['black','royal','purple','red','maroon','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '5402': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal','purple','maroon','navy','dark green'], Colors: ['royal','purple','maroon','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '5403': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','purple','red','maroon','navy'], Colors: ['black','royal','grey','purple','red','maroon','navy'], Designs: ['design1'], FeeItem: ''},
 '5412': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '5421': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '5424': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '5475': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '5488': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','columbia','grey','white','red','navy','royal'], Colors: ['black','columbia','grey','white','red','navy','royal'], Designs: ['design1'], FeeItem: ''},
 '5546': { Process: 'sub', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design2','design5'], FeeItem: 'TOWEL01'},
 '5571': { Process: 'none', DefaultPrimaryColor: 'blue', CommonColors: ['blue','royal'], Colors: ['blue','royal'], Designs: ['design1'], FeeItem: ''},
 '5576': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '5701': { Process: 'dtg', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','maroon','athletic gold','dark green','royal','navy','purple','black','grey','white','orange'], Designs: ['design1','design2','design3'], FeeItem: 'TMPLTD2G'},
 '5708': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '5712': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['grey','black'], Designs: ['design1'], FeeItem: ''},
 '5713': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','purple','white','red','maroon','navy','gold','dark green'], Colors: ['royal','grey','purple','white','red','maroon','navy','gold','dark green'], Designs: ['design1'], FeeItem: ''},
 '5715': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','grey','red','navy','gold'], Colors: ['black','royal','grey','red','navy','gold'], Designs: ['design1'], FeeItem: ''},
 '5717': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','purple','red','maroon','orange','navy','gold','dark green'], Colors: ['black','royal','grey','purple','red','maroon','orange','navy','gold','dark green'], Designs: ['design1'], FeeItem: ''},
 '5718': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','white','red','navy'], Colors: ['royal','grey','white','red','navy'], Designs: ['design1'], FeeItem: ''},
 '5721': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','purple','orange'], Colors: ['grey','purple','orange'], Designs: ['design1'], FeeItem: ''},
 '5722': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal'], Colors: ['royal'], Designs: ['design1'], FeeItem: ''},
 '5725': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','purple','red','orange','navy'], Colors: ['royal','grey','purple','red','orange','navy'], Designs: ['design1'], FeeItem: ''},
 '5726': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','red','orange'], Colors: ['black','grey','red','orange'], Designs: ['design1'], FeeItem: ''},
 '5728': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','purple','white','orange'], Colors: ['royal','grey','purple','white','orange'], Designs: ['design1'], FeeItem: ''},
 '5729': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red','orange'], Colors: ['red','orange'], Designs: ['design1'], FeeItem: ''},
 '5730': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal'], Colors: ['royal'], Designs: ['design1'], FeeItem: ''},
 '5731': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal','purple','red','orange'], Colors: ['royal','purple','red','orange'], Designs: ['design1'], FeeItem: ''},
 '5732': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','columbia','royal','grey','navy','dark green'], Colors: ['black','columbia','royal','grey','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '5736': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['purple','white','orange','yellow'], Colors: ['purple','white','orange','yellow'], Designs: ['design1'], FeeItem: ''},
 '5737': { Process: 'none', DefaultPrimaryColor: 'dark green', CommonColors: ['dark green','pink'], Colors: ['dark green','pink'], Designs: ['design1'], FeeItem: ''},
 '5739': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '5745': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '5748': { Process: 'none', DefaultPrimaryColor: 'columbia', CommonColors: ['columbia','red'], Colors: ['columbia','red'], Designs: ['design1'], FeeItem: ''},
 '5754': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','red','navy'], Colors: ['black','royal','red','navy'], Designs: ['design1'], FeeItem: ''},
 '5764': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','athletic gold','dark green','royal','navy','black','white','orange'], Designs: ['headwear','mascot'], FeeItem: 'LogoHat01'},
 '5786': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple'], Colors: ['purple'], Designs: ['design1'], FeeItem: ''},
 '5794': { Process: 'none', DefaultPrimaryColor: 'columbia', CommonColors: ['columbia'], Colors: ['columbia'], Designs: ['design1'], FeeItem: ''},
 '5810': { Process: 'none', DefaultPrimaryColor: 'brown', CommonColors: ['light bone','brown'], Colors: ['light bone','brown'], Designs: ['design1'], FeeItem: ''},
 '5868': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','navy'], Colors: ['grey','navy'], Designs: ['design1'], FeeItem: ''},
 '5869': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','purple','red','maroon','orange','navy','dark green'], Colors: ['grey','purple','red','maroon','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '5879': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red'], Colors: ['red'], Designs: ['design1'], FeeItem: ''},
 '5894': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '5939': { Process: 'none', DefaultPrimaryColor: 'orange', CommonColors: ['orange','dark green'], Colors: ['orange','dark green'], Designs: ['design1'], FeeItem: ''},
 '5948': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','purple','white','red'], Colors: ['black','grey','purple','white','red'], Designs: ['design1'], FeeItem: ''},
 '5949': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '5950': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','purple','orange'], Colors: ['grey','purple','orange'], Designs: ['design1'], FeeItem: ''},
 '5953': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple'], Colors: ['purple'], Designs: ['design1'], FeeItem: ''},
 '5958': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '5962': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '5963': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['grey','black','white'], Designs: ['design1'], FeeItem: ''},
 '5964': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','onix'], Colors: ['black','grey','onix'], Designs: ['design1'], FeeItem: ''},
 '5965': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white','black'], Colors: ['white','black'], Designs: ['design1'], FeeItem: ''},
 '5969': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['khaki','grey','white','black','navy'], Colors: ['khaki','grey','white','black','navy'], Designs: ['design1'], FeeItem: ''},
 '5970': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white'], Colors: ['grey','white'], Designs: ['design1'], FeeItem: ''},
 '5972': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '5973': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '5974': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '5975': { Process: 'none', DefaultPrimaryColor: 'pink', CommonColors: ['pink'], Colors: ['pink'], Designs: ['design1'], FeeItem: ''},
 '5989': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple','maroon','dark green'], Colors: ['purple','maroon','dark green'], Designs: ['design1'], FeeItem: ''},
 '6018': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','purple','red','cardinal','navy','dark green'], Colors: ['black','grey','purple','red','cardinal','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6019': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','maroon','dark green','royal','navy','purple','black','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6020': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','purple','red','maroon','orange','navy','gold','dark green'], Colors: ['black','royal','grey','purple','red','maroon','orange','navy','gold','dark green'], Designs: ['design1'], FeeItem: ''},
 '6022': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','purple','white','red','maroon','navy','dark green','collegiate green'], Colors: ['royal','grey','purple','white','red','maroon','navy','dark green','collegiate green'], Designs: ['design1'], FeeItem: ''},
 '6036': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '6037': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '6043': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','red','navy'], Colors: ['black','royal','grey','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6101': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','red','navy'], Colors: ['grey','red','navy'],  Designs: ['design1'], FeeItem: ''},
 '6134': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','red','yellow','vivid yellow'], Colors: ['royal','grey','red','yellow','vivid yellow'], Designs: ['design1'], FeeItem: ''},
 '6135': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['navy','grey','white','red','orange','yellow','dark green'], Colors: ['navy','grey','white','red','orange','yellow','dark green'], Designs: ['design1'], FeeItem: ''},
 '6136': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6137': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','royal','white','orange'], Colors: ['black','royal','white','orange'], Designs: ['design1'], FeeItem: ''},
 '6138': { Process: 'none', DefaultPrimaryColor: 'navy', CommonColors: ['navy','royal'], Colors: ['navy','royal'], Designs: ['design1'], FeeItem: ''},
 '6139': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','white','red','navy'], Colors: ['black','royal','grey','white','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6140': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '6142': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','dark green','royal','navy','black','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6143': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['red','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6144': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','red'], Colors: ['royal','grey','red'], Designs: ['design1'], FeeItem: ''},
 '6145': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6146': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','navy','dark green'], Colors: ['black','royal','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6147': { Process: 'none', DefaultPrimaryColor: 'white',  CommonColors: ['black','purple','white','red','maroon','orange','navy','yellow','dark green','pink'], Colors: ['black','purple','white','red','maroon','orange','navy','yellow','dark green','pink'], Designs: ['design1'], FeeItem: ''},
 '6148': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '6151': { Process: 'none', DefaultPrimaryColor: 'grey',  CommonColors: ['grey','black'], Colors: ['grey','black'], Designs: ['design1'], FeeItem: ''},
 '6152': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['black','grey','white','navy','khaki'], Colors: ['black','grey','white','navy','khaki'], Designs: ['design1'], FeeItem: ''},
 '6154': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6182': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6186': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6188': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','pink'], Colors: ['black','pink'], Designs: ['design1'], FeeItem: ''},
 '6193': { Process: 'none', DefaultPrimaryColor: 'pink', CommonColors: ['pink','royal'], Colors: ['pink','royal'], Designs: ['design1'], FeeItem: ''},
 '6194': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple'], Colors: ['purple'], Designs: ['design1'], FeeItem: ''},
 '6200': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6208': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6215': { Process: 'ht', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['royal','black','grey','navy'], Designs: ['design8','design9'], FeeItem: 'Golfbag05'},
 '6217': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6231': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','red','navy'], Colors: ['black','royal','grey','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6309': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','white','red','navy'], Colors: ['royal','grey','white','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6335': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','purple','white','red','maroon','navy','dark green'], Colors: ['black','royal','grey','purple','white','red','maroon','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6341': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','navy','black','grey','white'], Designs: ['design1'], FeeItem: ''},
 '6343': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','purple','white','red','cardinal','navy','dark green'], Colors: ['black','royal','grey','purple','white','red','cardinal','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6344': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','maroon'], Colors: ['royal','grey','maroon'], Designs: ['design1'], FeeItem: ''},
 '6352': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','white','red','maroon','orange','navy','dark green'], Colors: ['black','royal','grey','white','red','maroon','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6353': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','purple','red','maroon','navy','dark green'], Colors: ['black','royal','grey','purple','red','maroon','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6354': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['royal','grey','red','navy'], Colors: ['royal','grey','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6358': { Process: 'none', DefaultPrimaryColor: 'royal', CommonColors: ['royal','red','navy','dark green'], Colors: ['royal','red','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6359': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','red','navy'], Colors: ['grey','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6361': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['red','navy','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6362': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6363': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6365': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '6367': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6368': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','white','royal','red','maroon','orange','navy','dark green'], Colors: ['black','grey','white','royal','red','maroon','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6399': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','white','red','navy'], Colors: ['black','royal','grey','white','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6411': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','orange'], Colors: ['black','royal','grey','orange'], Designs: ['design1'], FeeItem: ''},
 '6412': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['black','white','grey'], Colors: ['red','orange','royal','white','grey','black'], Designs: ['team','mascot'], FeeItem: 'Logo01'},
 '6413': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','white','red','core red','navy'], Colors: ['black','grey','white','red','core red','navy'], Designs: ['design1'], FeeItem: ''},
 '6414': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','navy'], Colors: ['grey','black','navy'], Designs: ['design1'], FeeItem: ''},
 '6415': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','dark green','navy','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6416': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['grey','black'], Designs: ['design1'], FeeItem: ''},
 '6417': { Process: 'none', DefaultPrimaryColor: 'red', CommonColors: ['red','kelly green'], Colors: ['red','kelly green'], Designs: ['design1'], FeeItem: ''},
 '6418': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','columbia','royal','grey','trace grey','red','navy'], Colors: ['black','columbia','royal','grey','trace grey','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6419': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','purple'], Colors: ['black','purple'], Designs: ['design1'], FeeItem: ''},
 '6420': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white','black'], Colors: ['white','black'], Designs: ['design1'], FeeItem: ''},
 '6421': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '6423': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','royal','white'], Colors: ['black','royal','white'], Designs: ['design1'], FeeItem: ''},
 '6425': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white','navy'], Colors: ['black','white','navy'], Designs: ['design1'], FeeItem: ''},
 '6426': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['khaki','grey','black','white'], Colors: ['khaki','black','grey','white','navy'], Designs: ['design1'], FeeItem: ''},
 '6427': { Process: 'none', DefaultPrimaryColor: 'khaki', CommonColors: ['khaki','white','grey','black','mid grey'], Colors: ['khaki','white','grey','black','mid grey'], Designs: ['design1'], FeeItem: ''},
 '6431': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6432': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6433': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white','royal'], Colors: ['white','royal'], Designs: ['design1'], FeeItem: ''},
 '6435': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['black','grey','white'], Designs: ['design1'], FeeItem: ''},
 '6436': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '6439': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6458': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6477': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6480': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6489': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','royal','red','maroon','navy','dark green'], Colors: ['grey','royal','red','maroon','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6490': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','dark green','royal','navy','purple','black','white','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6491': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['red','orange','athletic gold','dark green','royal','navy','purple','black'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6492': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['red','orange','athletic gold','dark green','royal','navy','purple','black'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6493': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','navy'], Colors: ['grey','black','navy'], Designs: ['design1'], FeeItem: ''},
 '6495': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6496': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','royal','purple','white','red','maroon','orange','navy','dark green'], Colors: ['black','royal','purple','white','red','maroon','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6497': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','royal','purple','red','maroon','orange','navy','dark green'], Colors: ['black','royal','purple','red','maroon','orange','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6498': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6499': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','maroon','yellow','dark green','royal','navy','purple','black','white','orange','athletic gold'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6500': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6501': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6503': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','royal'], Colors: ['grey','royal'], Designs: ['design1'], FeeItem: ''},
 '6504': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6505': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['black','grey'], Designs: ['design1'], FeeItem: ''},
 '6508': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '6518': { Process: 'dtg', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','charcoal'], Colors: ['red','royal','navy','black','grey','charcoal'], Designs: ['design1','design2','design3'], FeeItem: 'TMPLTD2G'},
 '6528': { Process: 'ht', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black','navy','royal'], Designs: ['design1','design10'], FeeItem: 'HEATTRAN01'  },
 '6530': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['white','black','grey'], Colors: ['black','grey','navy','red','royal','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'  },
 '6559': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','maroon','dark green','royal','navy','purple','black','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '655F': { Process: 'dtg', DefaultPrimaryColor: 'onix', CommonColors: ['onix','black'], Colors: ['red','royal','navy','onix','black'], Designs: ['design1','design2','design3','design4','design5'], FeeItem: 'TMPLTD2G'},
 '6560': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','red','navy'], Colors: ['black','royal','grey','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6561': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['red','orange','athletic gold','dark green','black'], Designs: ['headwear','mascot'], FeeItem: 'LOGO01'},
 '6565': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','yellow','dark green','royal','navy','purple','black','grey','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6566': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','dark green','royal','navy','purple','black','white','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6567': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black','navy','dark green'], Colors: ['black','navy','dark green'], Designs: ['design1'], FeeItem: ''},
 '6568': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','royal','grey','white','red','navy'], Colors: ['black','royal','grey','white','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6569': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '6570': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey','white','navy'], Colors: ['black','grey','white','navy'], Designs: ['design1'], FeeItem: ''},
 '6571': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','dark green','royal','navy','black','white','grey'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6572': { Process: 'none', DefaultPrimaryColor: 'purple', CommonColors: ['purple','red','navy'], Colors: ['purple','red','navy'], Designs: ['design1'], FeeItem: ''},
 '6573': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '6574': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6575': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '6576': { Process: 'emb', DefaultPrimaryColor: 'black', CommonColors: ['black','pink'], Colors: ['yellow','kelly green','royal','purple','black','orange','burgundy','dark green'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6580': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['royal','navy','purple','black','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6581': { Process: 'emb', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '6582': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','red','black'], Colors: ['grey','red','black'], Designs: ['design1'], FeeItem: ''},
 '6583': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','black','grey','white'], Designs: ['design1'], FeeItem: ''},
 '6584': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['red','black','white'], Designs: ['design1'], FeeItem: ''},
 '6692': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['red','royal','grey'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '6702': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['white','black','grey'], Colors: ['red','maroon','dark green','royal','purple','navy','white','grey','black'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '6710': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey'], Colors: ['navy','royal','maroon','red','black','grey'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '6783': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['white','black','grey'], Colors: ['navy','purple','royal','dark green','maroon','grey','red','white','black'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '6785': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['navy','royal','grey','red'], Designs: ['Script','Block','Collegiate','adidas','mascot'], FeeItem: 'LOGO01'},
 '7582': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['grey','black'], Colors: ['black','grey'], Designs: ['design1'], FeeItem: ''},
 '7583': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['grey','black'], Colors: ['black','grey'], Designs: ['design1'], FeeItem: ''},
 '7584': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['yellow','royal','black','white','orange'], Designs: ['design1'], FeeItem: ''},
 '7585': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['black','grey','white'], Designs: ['design1'], FeeItem: ''},
 '7589': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '7590': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black, white'], Colors: ['black, white'], Designs: ['design1'], FeeItem: ''},
 '7595': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black'], Colors: ['red','dark green','navy','black','grey'], Designs: ['headwear','mascot'], FeeItem: 'LogoHat01'},
 '7596': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['black','white','grey'], Colors: ['red','royal','navy','white','grey','black'], Designs: ['headwear','mascot'], FeeItem: 'LogoHat01'},
 '7597': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','royal','navy','black','grey','white'], Designs: ['design1'], FeeItem: ''},
 '7599': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: 'GLOVE01'},
 '7600': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '7601': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '7602': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '7603': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '7604': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '7605': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '7607': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '7608': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '8611': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '8612': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '8615': { Process: 'uv', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1','design6','design7'], FeeItem: '1BALLLOGOFEE06'},
 '8623': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '8624': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '8626': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '8627': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['white'], Colors: ['white'], Designs: ['design1'], FeeItem: ''},
 '8629': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '8638': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '8639': { Process: 'none', DefaultPrimaryColor: 'white', CommonColors: ['black','white'], Colors: ['black','white'], Designs: ['design1'], FeeItem: ''},
 '8640': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey'], Colors: ['grey'], Designs: ['design1'], FeeItem: ''},
 '8641': { Process: 'none', DefaultPrimaryColor: 'black', CommonColors: ['black'], Colors: ['black'], Designs: ['design1'], FeeItem: ''},
 '8881': { Process: 'dtg', DefaultPrimaryColor: 'grey', CommonColors: ['black','grey'], Colors: ['black','grey'], Designs: ['design1','design2','design3','design4','design5'], FeeItem: 'TMPLTD2G'},
 '9646': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','yellow','dark green','royal','navy','purple','black','grey','white','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'},
 '9647': { Process: 'none', DefaultPrimaryColor: 'grey', CommonColors: ['grey','white','black','navy'], Colors: ['grey','white','black','navy'], Designs: ['design1'], FeeItem: ''},
 '9648': { Process: 'emb', DefaultPrimaryColor: 'grey', CommonColors: ['grey','black','white'], Colors: ['red','maroon','athletic gold','dark green','royal','navy','black','grey','white','orange'], Designs: ['team','mascot'], FeeItem: 'LOGO01'}
};

    var listCount = 0;

    for (ip = 0; ip < list.length; ip++)
    {
        if(countInArray(list, list[ip]) > 1)
        {
            $.writeln( list[ip]);
            listCount++;
        }
    }

    function countInArray(array, what) {
        var count = 0;
        for (var i = 0; i < array.length; i++) {
            if (array[i] === what) {
                count++;
            }
        }
       return count;
    }

    $.writeln("list count: " + listCount);
    $.writeln("list count: " + list.length);

